env:
  commonjs: true
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
    "indent": ["error", 4],
    "no-console": "off",
    "brace-style": ["error", "stroustrup"],
    "template-curly-spacing": ["error", "always"],
    "max-len": ["error", { "code": 120 }],
}
